---
name: Lint code with ruff
run-name: ${{ github.actor }} | Running nox session ruff-lint via uv
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".gitignore"

jobs:
  ruff-lint:
    name: python
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-22.04]
        version: ["3.12", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.4.24
      
      - name: Set up Python
        run: uv python install

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Lint code
        run: uv run nox -s ruff-lint
